<?php $element->setAttribute('class', 'form-control ' . $element->getAttribute('class')); ?>

<div class="form-group <?php if($form->hasErrorElement($element)): ?>has-error<?php endif; ?>">
    <?= $this->formLabel($element) ?>
    <?= $this->formElement($element) ?>
    <?= $this->formElementErrors()->render($element, ['class' => 'help-block']) ?>
</div>

<?php $this->headLink()->appendStylesheet('http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote-bs4.css') ?>
<?php $this->headScript()->appendFile('http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote-bs4.js') ?>

<script type="text/javascript">
<?php $this->headScript()->captureStart() ?>
    $('.summernote').summernote({
        /*callbacks: {
    /*onChange: function(contents, $editable) {
        $('#<?php echo $element->getName(); ?>').val(contents);
      //console.log('onChange:', contents, $editable);
      console.log('onChange:', $('#<?php echo $element->getName(); ?>').val());
    }
  }*/
    });
<?php $this->headScript()->captureEnd() ?>
</script>