<section id="wrapper" class="error-page">
    <div class="error-box">
        <div class="error-body text-center">
            <h1>¿Te has perdido?</h1>
            <h3 class="text-uppercase">Seguramente no debes estar aca!</h3>
            <p class="text-muted m-t-30 m-b-30">Si te vuelve a aparecer este cartel, por favor comunicate con el administrador.</p>
            <a href="<?php echo $this->url('home'); ?>" class="btn btn-info btn-rounded waves-effect waves-light m-b-40">Volver a la home</a> </div>
        <footer class="footer text-center">2017 © MobileIA.</footer>
    </div>
</section>