<?php $this->headTitle($this->miaLayout()->get('profile_title', 'Mi Perfil')); ?>
<div class="row bg-title">
    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
        <h4 class="page-title">Mi perfil</h4> </div>
    <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
        <ol class="breadcrumb">
            <li><a href="<?php echo $this->url('home'); ?>">Inicio</a></li>
            <li class="active">Mi perfil</li>
        </ol>
    </div>
</div>
<?php echo $this->partial('mia-layout-elite/flash-messenger'); ?>
<!-- .row -->
<div class="row">
    <div class="col-md-4 col-xs-12">
        <div class="white-box">
            <div class="user-bg"> <img width="100%" alt="user" src="<?php echo $this->basePath('mia-layout-elite/plugins/images/large/img1.jpg'); ?>">
                <div class="overlay-box">
                    <div class="user-content">
                        <a href="javascript:void(0)">
                            <?php if ($this->identity()->photo != ''): ?>
                                <img src="<?php echo $this->identity()->photo; ?>" alt="user-img" class="thumb-lg img-circle">
                            <?php else: ?>
                                <img src="<?php echo $this->basePath('mia-layout-elite/plugins/images/users/varun.jpg'); ?>" alt="user-img" class="thumb-lg img-circle">
                            <?php endif; ?>
                        </a>
                        <h4 class="text-white"><?php echo $this->identity()->firstname ?> <?php echo $this->identity()->lastname ?></h4>
                        <h5 class="text-white"><?php echo $this->identity()->email ?></h5>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-8 col-xs-12">
        <div class="white-box">
            <ul class="nav customtab nav-tabs" role="tablist">
                <li role="presentation" class="nav-item"><a href="#settings" class="nav-link active" aria-controls="messages" role="tab" data-toggle="tab" aria-expanded="false"><span class="visible-xs"><i class="fa fa-cog"></i></span> <span class="hidden-xs">Datos Personales</span></a></li>
                <li role="presentation" class="nav-item"><a href="#password" class="nav-link" aria-controls="messages" role="tab" data-toggle="tab" aria-expanded="false"><span class="visible-xs"><i class="fa fa-cog"></i></span> <span class="hidden-xs">Cambiar contraseña</span></a></li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane active" id="settings">
                    <form class="form-horizontal form-material" method="post">
                        <div class="form-group">
                            <label class="col-md-12">Nombre</label>
                            <div class="col-md-12">
                                <input type="text" name="firstname" placeholder="Mauricio" class="form-control form-control-line" value="<?php echo $this->identity()->firstname ?>">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-12">Apellido</label>
                            <div class="col-md-12">
                                <input type="text" name="lastname" placeholder="Gutierrez" class="form-control form-control-line" value="<?php echo $this->identity()->lastname ?>">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="example-email" class="col-md-12">Email</label>
                            <div class="col-md-12">
                                <input disabled="disabled" type="email" placeholder="johnathan@admin.com" class="form-control form-control-line" name="example-email" id="example-email" value="<?php echo $this->identity()->email ?>">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-12">Telefono</label>
                            <div class="col-md-12">
                                <input type="text" name="phone" placeholder="123 456 7890" class="form-control form-control-line" value="<?php echo $this->identity()->phone ?>">
                            </div>
                        </div>
                        <!--<div class="form-group">
                            <label class="col-sm-12">Genero</label>
                            <div class="col-sm-12">
                                <select class="form-control form-control-line">
                                    <option>Masculino</option>
                                    <option>Femenino</option>
                                </select>
                            </div>
                        </div>-->

                        <div class="form-group">
                            <div class="col-sm-12">
                                <button class="btn btn-success">Actualizar datos</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="tab-pane" id="password">
                    <form class="form-horizontal form-material" action="<?php echo $this->url('change-password'); ?>" method="post">
                        <div class="form-group">
                            <label class="col-md-12">Contraseña actual</label>
                            <div class="col-md-12">
                                <input type="password" name="old-password" value="" class="form-control form-control-line">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-12">Nueva contraseña</label>
                            <div class="col-md-12">
                                <input type="password" name="new-password" value="" class="form-control form-control-line">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-12">Confirmar Nueva contraseña</label>
                            <div class="col-md-12">
                                <input type="password" name="re-password" value="" class="form-control form-control-line">
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-sm-12">
                                <button type="submit" class="btn btn-success">Cambiar contraseña</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /.row -->