<?php if ($this->pageCount): ?>
<?php if($this->route_param_extra){ $paramsExtras = $this->route_param_extra; }else{ $paramsExtras = array(); } ?>
<ul class="pagination m-t-10">
    <!--<li class="footable-page-arrow disabled">
        <a data-page="first" href="#first">«</a>
    </li>-->
    <?php if (isset($this->previous)): ?>
    <li class="footable-page-arrow">
        <a data-page="prev" href="<?= $this->url($this->route, array_merge($paramsExtras, ['page' => $this->previous])); ?>">‹</a>
    </li>
    <?php else: ?>
    <li class="footable-page-arrow disabled">
        <a data-page="prev" href="#prev">‹</a>
    </li>
    <?php endif; ?>
    
    <!-- Numbered page links -->
    <?php foreach ($this->pagesInRange as $page): ?>
        <?php if ($page != $this->current): ?>
            <li class="footable-page"><a data-page="<?= $page; ?>" href="<?= $this->url($this->route, array_merge($paramsExtras, ['page' => $page])); ?>"><?= $page; ?></a></li>
        <?php else: ?>
            <li class="footable-page active"><a data-page="<?= $page; ?>" href="#"><?= $page; ?></a></li>
        <?php endif; ?>
    <?php endforeach; ?>
    
    <?php if (isset($this->next)): ?>
    <li class="footable-page-arrow">
        <a data-page="next" href="<?= $this->url($this->route, array_merge($paramsExtras, ['page' => $this->next])); ?>">›</a>
    </li>
    <?php else: ?>
    <li class="footable-page-arrow disabled">
        <a data-page="next" href="#next">›</a>
    </li>
    <?php endif; ?>
    <!--<li class="footable-page-arrow">
        <a data-page="last" href="#last">»</a>
    </li>-->
</ul>
<?php endif; ?>