<?php // In any of your .phtml files:
 $flash = $this->flashMessenger();
 $flash->setMessageOpenFormat('<div%s>')
     ->setMessageSeparatorString('')
     ->setMessageCloseString('<button type="button" class="close" data-dismiss="alert" aria-hidden="true" style="top: -.75rem">
         <span aria-hidden="true">×</span>
     </button></div>');

 echo $flash->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));
 echo $flash->render('info',    array('alert', 'alert-dismissible', 'alert-info'));
 echo $flash->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
 echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success')); ?>
