<?= $this->doctype() ?>
<html>
    <head>
        <?= $this->headTitle('')->setTranslatorEnabled(false)->setSeparator(' - ')->setAutoEscape(false) ?>

        <?=
                $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=1, user-scalable=no')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        
        <?=
                //$this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
                $this->headLink()
                ->prependStylesheet($this->basePath('mia-layout-elite/css/colors/default.css'))
                ->prependStylesheet($this->basePath('mia-layout-elite/css/style.css'))
                ->prependStylesheet($this->basePath('mia-layout-elite/css/animate.css'))
                ->prependStylesheet($this->basePath('mia-layout-elite/plugins/morrisjs/morris.css'))
                ->prependStylesheet($this->basePath('mia-layout-elite/plugins/css-chart/css-chart.css'))
                ->prependStylesheet($this->basePath('mia-layout-elite/plugins/vectormap/jquery-jvectormap-2.0.2.css'))
                ->prependStylesheet($this->basePath('mia-layout-elite/plugins/sidebar-nav/dist/sidebar-nav.min.css'))
                ->prependStylesheet($this->basePath('mia-layout-elite/plugins/bootstrap-extension/css/bootstrap-extension.css'))
                ->prependStylesheet($this->basePath('mia-layout-elite/bootstrap/dist/css/bootstrap.min.css'))
        ?>

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
        <?php include('loading.phtml'); ?>
        <div id="wrapper">
            <?php include('topbar.phtml'); ?>
            <?php include('sidebar.phtml'); ?>
            <!-- Page Content -->
            <div id="page-wrapper">
                <div class="container-fluid">
                    <?= $this->content ?>
                </div>
                <!-- /.container-fluid -->
            </div>
            <!-- /#page-wrapper -->
            <?php include('footer.phtml'); ?>
        </div>
        
        <!-- Scripts -->
        <?=
                $this->headScript()
                ->prependFile($this->basePath('mia-layout-elite/js/dashboard2.js'))
                ->prependFile($this->basePath('mia-layout-elite/js/custom.min.js'))
                ->prependFile($this->basePath('mia-layout-elite/plugins/styleswitcher/jQuery.style.switcher.js'))
                ->prependFile($this->basePath('mia-layout-elite/plugins/jquery.easy-pie-chart/easy-pie-chart.init.js'))
                ->prependFile($this->basePath('mia-layout-elite/plugins/jquery.easy-pie-chart/dist/jquery.easypiechart.min.js'))
                ->prependFile($this->basePath('mia-layout-elite/plugins/jquery-sparkline/jquery.sparkline.min.js'))
                ->prependFile($this->basePath('mia-layout-elite/plugins/vectormap/jquery-jvectormap-world-mill-en.js'))
                ->prependFile($this->basePath('mia-layout-elite/plugins/vectormap/jquery-jvectormap-2.0.2.min.js'))
                ->prependFile($this->basePath('mia-layout-elite/plugins/morrisjs/morris.js'))
                ->prependFile($this->basePath('mia-layout-elite/plugins/raphael/raphael-min.js'))
                ->prependFile($this->basePath('mia-layout-elite/plugins/flot.tooltip/js/jquery.flot.tooltip.min.js'))
                ->prependFile($this->basePath('mia-layout-elite/plugins/flot/jquery.flot.js'))
                ->prependFile($this->basePath('mia-layout-elite/plugins/counterup/jquery.counterup.min.js'))
                ->prependFile($this->basePath('mia-layout-elite/plugins/waypoints/lib/jquery.waypoints.js'))
                ->prependFile($this->basePath('mia-layout-elite/js/waves.js'))
                ->prependFile($this->basePath('mia-layout-elite/js/jquery.slimscroll.js'))
                ->prependFile($this->basePath('mia-layout-elite/plugins/sidebar-nav/dist/sidebar-nav.min.js'))
                ->prependFile($this->basePath('mia-layout-elite/plugins/bootstrap-extension/js/bootstrap-extension.min.js'))
                ->prependFile($this->basePath('mia-layout-elite/bootstrap/dist/js/bootstrap.min.js'))
                ->prependFile($this->basePath('mia-layout-elite/bootstrap/dist/js/tether.min.js'))
                ->prependFile($this->basePath('mia-layout-elite/plugins/jquery/dist/jquery.min.js'))
        ?>
        
        <?= $this->inlineScript() ?>
    </body>
</html>