<?php if($this->identity()): ?>
<!-- Left navbar-header -->
<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse slimscrollsidebar">
        <?php $this->navigation()->menu()->setPartial('mia-layout-elite/menu/basic'); ?>
        <?php echo $this->navigation('Zend\Navigation\\' . $this->identity()->role)->menu() ?>
    </div>
</div>
<!-- Left navbar-header end -->
<?php endif; ?>