<!-- Navigation -->
<nav class="navbar navbar-default navbar-static-top m-b-0">
    <div class="navbar-header">
        <a class="navbar-toggle hidden-sm hidden-md hidden-lg " href="javascript:void(0)" data-toggle="collapse" data-target=".navbar-collapse"><i class="ti-menu"></i></a>
        <div class="top-left-part">
            <a class="logo" href="#">
                <b class="visible-xs">
                    <img src="<?php echo $this->basePath($this->miaLayout()->get('topbar_icon_img', 'mia-layout-elite/plugins/images/eliteadmin-logo.png')); ?>" alt="home" style="width: 40px; height: 40px;" />
                </b>
                <span class="hidden-xs" style="height: 60px; display: inline-block; padding: 10px;">
                    <img src="<?php echo $this->basePath($this->miaLayout()->get('topbar_logo_img', 'mia-layout-elite/plugins/images/eliteadmin-text.png')); ?>" alt="home" style="height: 40px;" />
                </span>
            </a>
        </div>
        <?php echo $this->phrases(); ?>
        <ul class="nav navbar-top-links navbar-right pull-right">
            <!--<li class="dropdown"> <a class="dropdown-toggle waves-effect waves-light" data-toggle="dropdown" href="#"><i class="icon-envelope"></i>
                    <div class="notify"><span class="heartbit"></span><span class="point"></span></div>
                </a>
                <ul class="dropdown-menu mailbox scale-up">
                    <li>
                        <div class="drop-title">You have 4 new messages</div>
                    </li>
                    <li>
                        <div class="message-center">
                            <a href="#">
                                <div class="user-img"> <img src="<?php echo $this->basePath('mia-layout-elite/plugins/images/users/pawandeep.jpg') ?>" alt="user" class="img-circle"> <span class="profile-status online pull-right"></span> </div>
                                <div class="mail-contnet">
                                    <h5>Pavan kumar</h5>
                                    <span class="mail-desc">Just see the my admin!</span> <span class="time">9:30 AM</span> </div>
                            </a>
                            <a href="#">
                                <div class="user-img"> <img src="../plugins/images/users/sonu.jpg" alt="user" class="img-circle"> <span class="profile-status busy pull-right"></span> </div>
                                <div class="mail-contnet">
                                    <h5>Sonu Nigam</h5>
                                    <span class="mail-desc">I've sung a song! See you at</span> <span class="time">9:10 AM</span> </div>
                            </a>
                            <a href="#">
                                <div class="user-img"> <img src="../plugins/images/users/arijit.jpg" alt="user" class="img-circle"> <span class="profile-status away pull-right"></span> </div>
                                <div class="mail-contnet">
                                    <h5>Arijit Sinh</h5>
                                    <span class="mail-desc">I am a singer!</span> <span class="time">9:08 AM</span> </div>
                            </a>
                            <a href="#">
                                <div class="user-img"> <img src="../plugins/images/users/pawandeep.jpg" alt="user" class="img-circle"> <span class="profile-status offline pull-right"></span> </div>
                                <div class="mail-contnet">
                                    <h5>Pavan kumar</h5>
                                    <span class="mail-desc">Just see the my admin!</span> <span class="time">9:02 AM</span> </div>
                            </a>
                        </div>
                    </li>
                    <li>
                        <a class="text-center" href="javascript:void(0);"> <strong>See all notifications</strong> <i class="fa fa-angle-right"></i> </a>
                    </li>
                </ul>
            </li>-->
            <!-- /.dropdown -->
            <li class="dropdown">
                <a class="dropdown-toggle profile-pic" data-toggle="dropdown" href="#">
                    <?php if($this->miaLayout()->get('show_user_photo', true)): ?>
                        <?php if ($this->identity() == null || $this->identity()->photo == ''): ?>
                            <img src="<?php echo $this->basePath('mia-layout-elite/plugins/images/users/d1.jpg'); ?>" class="img-circle" alt="<?php if($this->identity() != null): ?><?php echo $this->identity()->firstname; ?><?php else: ?>Anonimo<?php endif; ?> Image" width="36">
                        <?php else: ?>
                            <img src="<?php echo $this->identity()->photo; ?>" class="img-circle" alt="<?php if($this->identity() != null): ?><?php echo $this->identity()->firstname; ?><?php else: ?>Anonimo<?php endif; ?> Image" width="36">
                        <?php endif; ?>
                    <?php endif; ?>
                    <b class="hidden-xs"><?php if($this->identity() != null): ?><?php echo $this->identity()->firstname; ?><?php else: ?>Anonimo<?php endif; ?></b>
                </a>
                <ul class="dropdown-menu dropdown-user scale-up">
                    <li>
                        <a href="<?php echo $this->url('profile'); ?>"><i class="ti-user"></i> Mi Perfil</a>
                    </li>
                    <li role="separator" class="divider"></li>
                    <!--<li>
                        <a href="#"><i class="ti-settings"></i> Configuración</a>
                    </li>
                    <li role="separator" class="divider"></li>-->
                    <li>
                        <a href="<?php echo $this->url('logout'); ?>"><i class="fa fa-power-off"></i> Cerrar sesión</a>
                    </li>
                </ul>
                <!-- /.dropdown-user -->
            </li>
        </ul>
    </div>
    <!-- /.navbar-header -->
    <!-- /.navbar-top-links -->
    <!-- /.navbar-static-side -->
</nav>
